post_index:
    path:     /
    defaults: { _controller: "BlogBundle:Post:index" }
    methods:  GET

post_show:
    path:     /{id}/show
    defaults: { _controller: "BlogBundle:Post:show" }
    methods:  GET

post_new:
    path:     /create
    defaults: { _controller: "BlogBundle:Post:create" }
    methods:  [GET, POST]

post_edit:
    path:     /{id}/edit
    defaults: { _controller: "BlogBundle:Post:edit" }
    methods:  [GET, POST]

post_delete:
    path:     /{id}/delete
    defaults: { _controller: "BlogBundle:Post:delete" }
    methods:  DELETE

post_comment_new:
    path:     /comment
    defaults: { _controller: "BlogBundle:Post:comment" }
    methods:  [POST]
